services:

    nginx:
        container_name: undabot_nginx
        build: ./.docker/nginx
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '5004:80'

    php:
        container_name: undabot_php
        build: ./.docker/php
        volumes:
            - ./:/var/www/html

    mysql:
        container_name: undabot_mysql
        build: ./.docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=undabot"
            - "MYSQL_USER=undabot"
            - "MYSQL_PASSWORD=undabot"
        volumes:
            - db-data-undabot:/var/lib/mysql
            - ./:/app
        ports:
            - "33308:3306"

volumes:
    db-data-undabot:


