services:

    nginx:
        container_name: undabot_nginx
        build: ./.docker/nginx
        ports:
            - '5004:80'
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php:
        container_name: undabot_php
        build: ./.docker/php
        volumes:
            - ./:/var/www/html

