parameters:
    app.text_term_provider_github_issue.token: '%env(APP_TEXT_TERM_PROVIDER_GITHUB_ISSUE_TOKEN)%'
    app.text_term_provider_github_issue.url: '%env(APP_TEXT_TERM_PROVIDER_GITHUB_ISSUE_URL)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TextTerm\Provider\GithubIssueProvider:
        $token: '%app.text_term_provider_github_issue.token%'
        $url: '%app.text_term_provider_github_issue.url%'

    App\Service\TextTerm\Provider\ProviderInterface: '@App\Service\TextTerm\Provider\GithubIssueProvider'
