parameters:
    app.score_text_fetcher.github.token: '%env(APP_SCORE_TEXT_FETCHER_GITHUB_TOKEN)%'
    app.score_text_fetcher.github.username: '%env(APP_SCORE_TEXT_FETCHER_GITHUB_USERNAME)%'
    app.score_text_fetcher.github.repo: '%env(APP_SCORE_TEXT_FETCHER_GITHUB_REPO)%'
    app.score_text_fetcher.github.issue_id: '%env(APP_SCORE_TEXT_FETCHER_GITHUB_ISSUE_ID)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TextTerm\TextProvider\TextProviderInterface:
        class: App\Service\TextTerm\TextProvider\GithubIssueTextProvider

